version: '3.4'
services:
  pythonvortexbot:
    image: pythonvortexbot
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs:z
      - ./preferences:/app/preferences:z
      - ./temp:/app/temp:z
      - /var/www/html/fastdl/sound/ui:/var/www/html/fastdl/sound/ui:z
    restart: always